apiVersion: apps/v1
kind: Deployment
metadata:
  name: raccoon-deployment
spec:
  selector:
    matchLabels:
      app: raccoon
  template:
    metadata:
      labels:
        app: raccoon
    spec:
      containers:
        - name: raccoon
          image: raccoon:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: raccoon-secret
          ports:
            - containerPort: 8081
              name: http-raccoon
              protocol: TCP
          volumeMounts:
            - mountPath: /dicom-files
              name: raccoon-pv
      volumes:
        - name: raccoon-pv
          persistentVolumeClaim:
            claimName: raccoon-pvc
