apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  labels:
    app: grafana
type: Opaque
stringData:
  GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "password"
  GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
  GF_SERVER_SERVE_FROM_SUB_PATH: "true"
